[package]
name = "sad"
version = "0.4.18"
description = "Space Age seD | https://github.com/ms-jpq/sad"
authors = ["git@bigly.dog"]
edition = "2021"

[build-dependencies]
uuid = { version = "0.8", features = ["v4"] }

[dependencies]
aho-corasick = "0.7"
ansi_term = "0.12"
async-channel = "1.6"
atty = "0.2"
difflib = "0.4"
futures = "0.3"
num_cpus = "1"
pathdiff = "0.2"
regex = "1"
shlex = "1"
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
which = "4"
