name: sad

base: core20

version: "{{ version }}"

summary: |-
  {{ desc | indent(2) }}

description: |-
  {{ long_desc | indent(2) }}

apps:
  sad:
    command: sad

parts:
  sad:
    plugin: rust
    source: "{{ repo }}"
    stage-packages:
      - fzf
