name: sad

base: core20

version: "{{ version }}"

summary: |-
  {{ desc | indent(2) }}

description: |-
  {{ long_desc | indent(2) }}

grade: stable
confinement: devmode

apps:
  sad:
    command: sad

parts:
  sad:
    plugin: rust
    source: "{{ repo }}"
