---
name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install -U mypy types-PyYAML types-toml types-Jinja2

      - name: Lint
        run: mypy -- .

  build:
    strategy:
      matrix:
        jobs:
          - runner: ubuntu-latest
            triple: x86_64-pc-windows-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-musl

          - runner: macos-latest
            triple: x86_64-apple-darwin
    runs-on: ${{ matrix.jobs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install --requirement ./requirements.txt

      - name: Deps
        run: ./build.py deps

      - name: Build
        run: ./build.py buildr -- ${{ matrix.jobs.triple }}

      - name: Upload Bin
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jobs.triple }}
          path: artifacts/${{ matrix.jobs.triple }}.zip

      - name: Upload Deb
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jobs.triple }}.deb
          path: artifacts/${{ matrix.jobs.triple }}.deb

  arts:
    needs:
      - build
    strategy:
      matrix:
        triples:
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts Zip
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.triple }}.zip
          path: artifacts

      - name: Download Artifacts Deb
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.triple }}.deb
          path: artifacts

  install_macos:
    runs-on: macos-latest

    steps:
      - name: Homebrew
        run: brew install ms-jpq/sad/sad

      - name: Confirm Install
        run: brew list -1
