---
name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install -U mypy types-PyYAML types-toml types-Jinja2

      - name: Lint
        run: mypy -- .

  build:
    strategy:
      matrix:
        jobs:
          - runner: ubuntu-latest
            triple: x86_64-pc-windows-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-musl

          - runner: macos-latest
            triple: x86_64-apple-darwin
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deps
        run: ./build.py deps

      - name: Build
        run: ./build.py buildr -- ${{ matrix.job.triple }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.job.triple }}
          path: artifacts/${{ matrix.job.triple }}.zip

  build_debs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./ci/docker.py deb

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sad-deb
          path: artifacts/sad.deb

  install_macos:
    runs-on: macos-latest

    steps:
      - name: Homebrew
        run: brew install ms-jpq/sad/sad

      - name: Confirm Install
        run: brew list -1
