---
name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Lint
        run: |-
          make lint

  build:
    strategy:
      matrix:
        jobs:
          - runner: ubuntu-latest
            triple: aarch64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: aarch64-unknown-linux-musl

          - runner: ubuntu-latest
            triple: x86_64-pc-windows-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-musl

          - runner: macos-latest
            triple: aarch64-apple-darwin

          - runner: macos-latest
            triple: x86_64-apple-darwin

          - runner: windows-latest
            triple: aarch64-pc-windows-msvc

          - runner: windows-latest
            triple: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.jobs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Deps
        run: |-
          make deps

      - name: Build
        run: |-
          make release TRIPLE=${{ matrix.jobs.triple }}

      - name: Upload Bin
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.jobs.triple }}.zip
          path: artifacts/${{ matrix.jobs.triple }}.zip

      - name: Upload Deb
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.jobs.triple }}.deb
          path: artifacts/${{ matrix.jobs.triple }}.deb

  arts:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./arts/

  install_macos:
    runs-on: macos-latest

    steps:
      - name: Homebrew
        run: brew install ms-jpq/sad/sad

      - name: Confirm Install
        run: brew list -1
