---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci.yml

  release:
    permissions:
      contents: write

    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./arts/

      - name: Create Release
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          make ci
