---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ci.yml

  release:
    permissions:
      contents: write

    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ">= 0"

      - uses: actions/download-artifact@v4
        with:
          path: ./arts/

      - env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          make ci
