---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install -U mypy types-PyYAML types-toml types-Jinja2

      - name: Lint
        run: mypy -- .

  build:
    strategy:
      matrix:
        jobs:
          - runner: ubuntu-latest
            triple: aarch64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: aarch64-unknown-linux-musl

          - runner: ubuntu-latest
            triple: x86_64-pc-windows-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-musl

          # - runner: macos-latest
          #   triple: aarch64-apple-darwin

          - runner: macos-latest
            triple: x86_64-apple-darwin

    runs-on: ${{ matrix.jobs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install --requirement ./requirements.txt

      - name: Deps
        run: ./build.py deps

      - name: Build
        run: ./build.py buildr -- ${{ matrix.jobs.triple }}

      - name: Upload Bin
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jobs.triple }}.zip
          path: artifacts/${{ matrix.jobs.triple }}.zip

      - name: Upload Deb
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jobs.triple }}.deb
          path: artifacts/${{ matrix.jobs.triple }}.deb

  release:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install --requirement ./requirements.txt

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./arts/

      - name: Create Release
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./ci/release.py
