---

name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        jobs:
          - runner: ubuntu-latest
            triple: x86_64-pc-windows-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-gnu

          - runner: ubuntu-latest
            triple: x86_64-unknown-linux-musl

          - runner: macos-latest
            triple: x86_64-apple-darwin
    runs-on: ${{ matrix.jobs.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install --requirement ./requirements.txt

      - name: Deps
        run: ./build.py deps

      - name: Build
        run: ./build.py buildr -- ${{ matrix.jobs.triple }}

      - name: Upload Bin
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jobs.triple }}
          path: artifacts/${{ matrix.jobs.triple }}.zip

      - name: Upload Deb
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.jobs.triple }}.deb
          path: artifacts/${{ matrix.jobs.triple }}.deb

  release:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts macos
        uses: actions/download-artifact@v2
        with:
          name: sad-macos
          path: artifacts

      - name: Download Artifacts ubuntu
        uses: actions/download-artifact@v2
        with:
          name: sad-linux
          path: artifacts

      - name: Download Artifacts debian deb
        uses: actions/download-artifact@v2
        with:
          name: sad-deb
          path: artifacts

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Pip Packages
        run: pip install --requirement ./requirements.txt

      - name: Set ENV
        id: set_env
        run: ./ci/ci.py --release

      - name: Create Release
        id: new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ fromJSON(steps.set_env.outputs.RELEASE_INFO).tag_name }}
          release_name: ${{ fromJSON(steps.set_env.outputs.RELEASE_INFO).release_name }}
          body: ${{ fromJSON(steps.set_env.outputs.RELEASE_INFO).release_notes }}
          draft: false
          prerelease: false

      - name: Upload Asset - Macos
        id: asset_macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_path: artifacts/sad-macos.zip
          asset_name: x86_64-apple-darwin.zip

      - name: Upload Asset - Ubuntu
        id: asset_ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/zip
          asset_path: artifacts/sad-linux.zip
          asset_name: x86_64-unknown-linux-gnu.zip

      - name: Upload Asset - Debian deb
        id: asset_debian
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.new_release.outputs.upload_url }}
          asset_content_type: application/vnd.debian.binary-package
          asset_path: artifacts/sad.deb
          asset_name: x86_64-unknown-linux-gnu.deb

      - name: Homebrew
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: >-
          ./ci/release.py
          --brew-artifact sad-macos.zip
          --brew-uri ${{ steps.asset_macos.outputs.browser_download_url }}

      - name: Snapcraft
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
        run: >-
          ./ci/release.py
          --snapcraft

